// Generated by CoffeeScript 1.10.0
(function() {
  var api, app, express, parser;

  express = require('express');

  parser = require('body-parser');

  app = express();

  app.use(express["static"]('.'));

  app.use(parser.json());

  app.use(parser.urlencoded({
    extended: true
  }));

  api = require('./api.json');

  app.post('/api/authentications', function(req, res) {
    var auth;
    auth = req.body.authentication;
    switch (false) {
      case !(auth.username === 'mitch@rocketmade.com' && auth.password === 'password'):
        return res.status(200).json(api.authentications.create.pass);
      default:
        return res.status(400).json(api.authentications.create.fail);
    }
  });

  app.listen(3010);

}).call(this);
